### ISSUE TITLE
File Input Processor throws multiple dragonfly_io_read() errors

### ISSUE THREAD

**Issue by notslow** [counterflow-ai/dragonfly-mle#2]
The file input processor produces multiple errors in the output stream when used.  In addition, the data in the input file is repeated over and over in the output file. 

> dragonfly: lua_flywheel_loop: dragonfly_io_read() error
> dragonfly: lua_flywheel_loop: dragonfly_io_read() error
> dragonfly: lua_flywheel_loop: dragonfly_io_read() error
> dragonfly: lua_flywheel_loop: dragonfly_io_read() error
> ...

[file-test-config.lua.txt](https://github.com/counterflow-ai/dragonfly-mle/files/2250453/file-test-config.lua.txt)
[no-op-filter.lua.txt](https://github.com/counterflow-ai/dragonfly-mle/files/2250454/no-op-filter.lua.txt)
[sample-flow-events.json.txt](https://github.com/counterflow-ai/dragonfly-mle/files/2250455/sample-flow-events.json.txt)

**Comment by shieldwolfone** [comment]
Fixed.
