### ISSUE TITLE
compilation problem on master branch

### ISSUE THREAD

**Issue by jerome-plumecoq** [counterflow-ai/dragonfly-mle#7]
Hello,

Docker build for dragonfly-mle fails (master branch) with this compilation error : 

> 
> 
> 
> (master)$ docker build -t dragonfly .
> Sending build context to Docker daemon  3.946MB
> Step 1/14 : FROM debian:stretch-slim
>  ---> 9a4a82cec2d2
> Step 2/14 : LABEL  maintainer="mle@counterflowai.com" domain="counterflow.ai"
>  ---> Using cache
>  ---> b6274ed871d7
> Step 3/14 : RUN apt-get update --fix-missing
>  ---> Using cache
>  ---> e9d0c52de534
> Step 4/14 : RUN apt-get install -y zlib1g-dev libluajit-5.1 liblua5.1-dev lua-socket libcurl4-openssl-dev libatlas-base-dev libhiredis-dev git make libmicrohttpd-dev
>  ---> Using cache
>  ---> cabeecea1176
> Step 5/14 : RUN git clone https://github.com/counterflow-ai/dragonfly-mle;     cd dragonfly-mle/src; make ; make install
>  ---> Running in ddb61820295c
> Cloning into 'dragonfly-mle'...
> cc -O2 -Wall -march=native -Werror -Wno-error=tautological-pointer-compare -DMLE_VERSION=\"v0.6.8\" -I. -I/usr/local/include -I./io -I./test -I./lib/msgqueue -I./resp -I./lib/lua-cjson -I./lib/lua-hiredis -I./lib/lua-cmsgpack -c main.c  -o main.o
> cc1: error: -Werror=tautological-pointer-compare: no option -Wtautological-pointer-compare
> Makefile:117: recipe for target 'main.o' failed
> make: *** [main.o] Error 1
> installing files
> install -d /usr/local/dragonfly-mle/bin/ 
> install -d /usr/local/dragonfly-mle/config/
> install -d /usr/local/dragonfly-mle/filter/
> install -d /usr/local/dragonfly-mle/analyzer/
> install -d /usr/local/dragonfly-mle/www/
> install ./dragonfly-mle /usr/local/dragonfly-mle/bin/
> install: cannot stat './dragonfly-mle': No such file or directory
> Makefile:95: recipe for target 'install' failed
> make: *** [install] Error 1
> The command '/bin/sh -c git clone https://github.com/counterflow-ai/dragonfly-mle;     cd dragonfly-mle/src; make ; make install' returned a non-zero code: 2
>

**Comment by counterflowai** [comment]
Thanks for submitting an issue ticket.

A fix [https://github.com/counterflow-ai/dragonfly-mle/pull/8](https://github.com/counterflow-ai/dragonfly-mle/pull/8) has already been pushed and is going through our screening process before merging into `devel` and `master`.

Feel free to use the `dockerfile-fix` branch and let us know if you are still having issues.

Best regards,
Max

**Comment by jerome-plumecoq** [comment]
thank you very much it's fine with your fix.
