### ISSUE TITLE
dragonfly run error

### ISSUE THREAD

**Issue by jerome-plumecoq** [counterflow-ai/dragonfly-mle#9]
Hi,

I try running dragonfly-mle in a docker environment (with default configuration) and I have an Illegal instruction :

> $ ./dragonfly-mle -v
> dragonfly: version: v0.6.5-11-gb20a
> version: /var/log/dragonfly-mle
> dragonfly: log dir: /var/log/dragonfly-mle
> log dir: /var/log/dragonfly-mle
> dragonfly: analyzer dir: /usr/local/dragonfly-mle/analyzer
> analyzer dir: /usr/local/dragonfly-mle/analyzer
> dragonfly: config file: /usr/local/dragonfly-mle/config/config.lua
> config file: /usr/local/dragonfly-mle/config/config.lua
> dragonfly: load_redis_modules: no redis modules listed
> root directory: /usr/local/dragonfly-mle
> dragonfly: root directory: /usr/local/dragonfly-mle
> dragonfly: Running eve
> dragonfly: eve: opening tail:///data/extraction/eve/gcap-dev3-185-jpl.gatewatcher.com/eve-1550510533.log
> lua_input_thread:  default_analyzer: alert
> dragonfly: Loaded /usr/local/dragonfly-mle/analyzer/example-nsm.lua
> Illegal instruction
>

**Comment by MaxOrelus** [comment]
Hi Jerome,

For me to better help troubleshoot the issue, do you mind providing the following information:

* docker version
* branch docker image was built from
* base OS you are running docker on (host)
* `gcap-dev3-185-jpl.gatewatcher.com/eve-1550510533.log` - is the format of this file similar to eve.json (JSON object/per line)

**Comment by jerome-plumecoq** [comment]
> Hi Jerome,

Hi Maxorelus,

The file `gcap-dev3-185-jpl.gatewatcher.com/eve-1550510533.log` is a eve.json file, with one JSON object/per line.
I build docker image (with my own Dockerfile, from devel branch) on my laptop (Ubuntu 16.04, with docker 18.09.2) and running it on another platform. 
I solved the problem by modifying a line in the Makefile : 

`LINUX_CFLAGS = -O2 -Wall -march=nehalem -Werror
` 
instead of :

`LINUX_CFLAGS = -O2 -Wall -march=native -Werror
` 

thank you very much !

> For me to better help troubleshoot the issue, do you mind providing the following information:
> 
>     * docker version
> 
>     * branch docker image was built from
> 
>     * base OS you are running docker on (host)
> 
>     * `gcap-dev3-185-jpl.gatewatcher.com/eve-1550510533.log` - is the format of this file similar to eve.json (JSON object/per line)
